name: Rust

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2.8.2
        with:
          shared-key: rust-${{ hashFiles('**/Cargo.lock') }}
          add-job-id-key: false
          add-rust-environment-hash-key: false
          cache-on-failure: false
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo clippy --workspace --tests --examples -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.8.2
        with:
          shared-key: rust-${{ hashFiles('**/Cargo.lock') }}
          add-job-id-key: false
          add-rust-environment-hash-key: false
          cache-on-failure: false
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo test --workspace

  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-docs
      - uses: Swatinem/rust-cache@v2.8.2
        with:
          shared-key: rust-${{ hashFiles('**/Cargo.lock') }}
          add-job-id-key: false
          add-rust-environment-hash-key: false
          cache-on-failure: false
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo doc --workspace --no-deps

